"""
Fit (scale, threshold) on a calibration split, predict the result, write the config.

The counterpart of tau_deploy.py for the scaled-argmax rule. It produces three
things and its whole purpose is that the first two are checkable against the
third:

  <md>          the PREDICTION -- what eval.py should print, from the cache alone
  <split>.txt   the held-out tiles, so the baseline is measured on the same pixels
  <cfg>.py      an mmseg config carrying `class_scale` AND `prob_thd` as lists

⚠️ Run verify_argmax_reorder.py FIRST. It proves the histogram arithmetic below
and the segmentor's rule are the same thing. Without that, a disagreement between
this prediction and eval.py has two possible causes and no way to tell them apart.

⭐ THREE numbers get predicted, not two, because the question is not "does this
beat the published baseline" -- per-class tau already does that. It is "does the
scale add anything ON TOP of the thresholds":

    published tau, no scale     the baseline
    per-class tau, no scale     the existing method
    per-class tau + scale       this

All three on the SAME held-out tiles. The middle row is the one the last row must
beat, and eval.py can reproduce all three from the two configs this writes plus
the base config with an ann_file override.

    python scripts/verify_argmax_reorder.py            # CPU, must pass first
    python scripts/reorder_deploy.py \\
        --cache ~/outputs/loveda_full_all/cache --tau 0.5 --calib 200 --seed 0 \\
        --split-out ~/splits/loveda_reorder_heldout.txt \\
        --cfg-out ~/SegEarth-OV-3/configs/cfg_loveda_reorder.py \\
        --tau-cfg-out ~/SegEarth-OV-3/configs/cfg_loveda_tauonly.py \\
        --md ~/outputs/week4/reorder_deploy.md
"""
import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import labels                                                     # noqa: E402
from tau_oracle import confusion_at, per_class_iou, miou, NBINS   # noqa: E402
from tau_cv import fit as fit_tau                                 # noqa: E402
from argmax_reorder import hist_at, fit_scale, load_full          # noqa: E402


CFG = '''# GENERATED by scripts/reorder_deploy.py -- do not hand-edit.
#
# Fitted on {ncal} calibration tiles (seed {seed}); evaluated on the {nheld}
# DISJOINT tiles listed in the ann_file below.
#
# Predicted from the cached score stack, on those held-out tiles:
#     published tau = {tau}, no scale  ->  mIoU {m_pub:.2f}
#     per-class tau, no scale          ->  mIoU {m_tau:.2f}   ({d_tau:+.2f})
#     per-class tau + class_scale      ->  mIoU {m_all:.2f}   ({d_all:+.2f})
#
# The row that matters is the third against the SECOND: {d_inc:+.2f}. Beating the
# first proves nothing, because per-class tau already does.
_base_ = './{base_cfg}'

model = dict(
    classname_path='./configs/{cls_file}',
    confidence_threshold=0.5,
    # applied to the scores BEFORE the argmax, in the order of {cls_file}:
{scale_comment}
    class_scale=[{scale_list}],
    # applied to the RAW winning score after it, same order:
{thd_comment}
    prob_thd=[{thd_list}],
)

test_dataloader = dict(
    dataset=dict(ann_file='{split}'))
'''

TAU_CFG = '''# GENERATED by scripts/reorder_deploy.py -- the MIDDLE rung.
#
# Per-class thresholds with NO scaling, on the same {nheld} held-out tiles, so the
# scale's contribution is measurable rather than inferred. Predicted mIoU {m_tau:.2f}.
_base_ = './{base_cfg}'

model = dict(
    classname_path='./configs/{cls_file}',
    confidence_threshold=0.5,
{thd_comment}
    prob_thd=[{thd_list}],
)

test_dataloader = dict(
    dataset=dict(ann_file='{split}'))
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache', required=True, help='a --cache-full cache')
    ap.add_argument('--tau', type=float, required=True, help='the published τ')
    ap.add_argument('--calib', type=int, default=200)
    ap.add_argument('--subsample', type=int, default=40000)
    ap.add_argument('--objective', choices=['all', 'real'], default='real')
    ap.add_argument('--w-rounds', type=int, default=3)
    ap.add_argument('--tau-rounds', type=int, default=3)
    ap.add_argument('--seed', type=int, default=0)
    ap.add_argument('--split-out', required=True)
    ap.add_argument('--cfg-out', default=None)
    ap.add_argument('--tau-cfg-out', default=None)
    ap.add_argument('--base-cfg', default='cfg_loveda.py')
    ap.add_argument('--cls-file', default='cls_loveda.txt')
    ap.add_argument('--md', default=None)
    args = ap.parse_args()

    LB = labels.from_cache(args.cache)
    nc, bg = LB.n, LB.bg - 1
    print(f'  classes: {LB}')

    files = sorted(Path(args.cache).expanduser().glob('*.npz'))
    T = len(files)
    if args.calib >= T:
        raise SystemExit(f'--calib {args.calib} but only {T} tiles')
    print(f'{T} tiles | published τ = {args.tau} | calib {args.calib}\n')

    rng = np.random.default_rng(args.seed)
    S, G, PT = load_full(files, args.subsample, nc, NBINS, rng)

    idx = rng.permutation(T)
    cal, held = idx[:args.calib], idx[args.calib:]

    # ---- the held-out tile list, written before anything is fitted on it
    stems = sorted(files[i].stem for i in held)
    sp = Path(args.split_out).expanduser()
    sp.parent.mkdir(parents=True, exist_ok=True)
    sp.write_text('\n'.join(stems) + '\n')
    print(f'\nheld-out split -> {sp}  ({len(stems)} tiles)')

    Scal, Gcal = S[cal].reshape(-1, nc), G[cal].reshape(-1)
    Shel, Ghel = S[held].reshape(-1, nc), G[held].reshape(-1)
    ones = np.ones(nc)

    # ---- rung 1 and 2: no scale. EXACT, from the per-tile histograms.
    Hh = PT[held].sum(0).astype(np.int64)
    taus_only = fit_tau(PT[cal].sum(0).astype(np.int64), bg, NBINS,
                        objective=args.objective)
    m_pub = miou(confusion_at(Hh, np.full(nc, args.tau), bg, NBINS))
    m_tau = miou(confusion_at(Hh, taus_only, bg, NBINS))

    # ---- rung 3: fit the scale, then refit tau underneath it
    print('\nfitting the scale:')
    w, _ = fit_scale(Scal, Gcal, bg, nc, NBINS, np.round(
        np.exp(np.linspace(np.log(0.40), np.log(2.50), 11)), 3),
        args.objective, args.w_rounds, args.tau_rounds)
    taus_all = fit_tau(hist_at(Scal, Gcal, w, nc, NBINS), bg, NBINS,
                       objective=args.objective)
    Hh_w = hist_at(Shel, Ghel, w, nc, NBINS)
    m_all = miou(confusion_at(Hh_w, taus_all, bg, NBINS))

    # ⚠️ rung 3 is computed on SUBSAMPLED pixels while rungs 1-2 are exact, so
    # the same subsample is used to re-measure rung 2. Mixing an exact number
    # with a subsampled one would attribute the sampling difference to the scale.
    Hh_sub = hist_at(Shel, Ghel, ones, nc, NBINS)
    m_tau_sub = miou(confusion_at(Hh_sub, taus_only, bg, NBINS))
    m_pub_sub = miou(confusion_at(Hh_sub, np.full(nc, args.tau), bg, NBINS))
    drift = abs((m_tau - m_pub) - (m_tau_sub - m_pub_sub))

    pc_tau = per_class_iou(confusion_at(Hh, taus_only, bg, NBINS)) \
        - per_class_iou(confusion_at(Hh, np.full(nc, args.tau), bg, NBINS))
    pc_all = per_class_iou(confusion_at(Hh_w, taus_all, bg, NBINS)) \
        - per_class_iou(confusion_at(Hh_sub, taus_only, bg, NBINS))

    d_tau, d_all = m_tau - m_pub, m_all - m_pub
    d_inc = m_all - m_tau_sub

    md = ['# Scaled argmax — deployment fit and prediction\n',
          f'- cache: `{args.cache}`  |  tiles: **{T}**  |  calibration: '
          f'**{args.calib}**, held out: **{len(stems)}** (seed {args.seed})',
          f'- published τ: **{args.tau}**  |  objective **`{args.objective}`**\n',
          '## Predicted, on the held-out tiles\n',
          '| rung | scale | thresholds | mIoU |', '|---|---|---|---|',
          f'| baseline | — | published {args.tau} | {m_pub:.2f} |',
          f'| **per-class τ** | — | fitted | **{m_tau:.2f}** ({d_tau:+.2f}) |',
          f'| **+ class scale** | fitted | fitted | **{m_all:.2f}** ({d_all:+.2f}) |',
          f'\n⭐ **The increment that matters is {d_inc:+.2f}** — the scale over the '
          'thresholds, both measured on the same subsampled pixels. Beating the '
          'baseline proves nothing here; per-class τ already does that.\n',
          f'⚠️ Rungs 1–2 are exact over every pixel; rung 3 is over a '
          f'{args.subsample}-px/tile subsample. Rung 2 recomputed on that same '
          f'subsample gives {m_tau_sub:.2f}, a drift of **{drift:.3f}** mIoU — the '
          'increment above uses the subsampled rung 2, so the sampling difference '
          'is not credited to the scale.\n']

    md += ['## Fitted parameters\n', '| class | scale | threshold |', '|---|---|---|']
    for c in range(nc):
        md.append(f'| {LB.names[c]}{" *(catch-all)*" if c == bg else ""} | '
                  f'**{w[c]:.3f}** | {taus_all[c]:.3f} |')

    md += ['\n## Predicted per-class Δ IoU\n',
           '| class | τ over baseline | scale over τ |', '|---|---|---|']
    for c in range(nc):
        if np.isfinite(pc_tau[c]) or np.isfinite(pc_all[c]):
            md.append(f'| {LB.names[c]} | {pc_tau[c]:+.2f} | **{pc_all[c]:+.2f}** |')

    # ---- configs
    def block(vals, fmt='{:.3f}'):
        return '\n'.join(f'    #   {LB.names[c]:<14} {fmt.format(vals[c])}'
                         for c in range(nc))

    written = []
    if args.tau_cfg_out:
        p = Path(args.tau_cfg_out).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(TAU_CFG.format(
            nheld=len(stems), m_tau=m_tau, base_cfg=args.base_cfg,
            cls_file=args.cls_file, thd_comment=block(taus_only), split=sp,
            thd_list=', '.join(f'{t:.3f}' for t in taus_only)))
        written.append(p)
    if args.cfg_out:
        p = Path(args.cfg_out).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(CFG.format(
            ncal=args.calib, seed=args.seed, nheld=len(stems), tau=args.tau,
            m_pub=m_pub, m_tau=m_tau, m_all=m_all, d_tau=d_tau, d_all=d_all,
            d_inc=d_inc, base_cfg=args.base_cfg, cls_file=args.cls_file,
            scale_comment=block(w), scale_list=', '.join(f'{x:.3f}' for x in w),
            thd_comment=block(taus_all), split=sp,
            thd_list=', '.join(f'{t:.3f}' for t in taus_all)))
        written.append(p)

    if written:
        md += ['\n## Run it — three passes, same tiles\n', '```bash',
               'cd ~/SegEarth-OV-3',
               '# 1. baseline, restricted to the held-out tiles',
               f'python eval.py ./configs/{args.base_cfg} \\',
               f'  --cfg-options test_dataloader.dataset.ann_file={sp}']
        if args.tau_cfg_out:
            md += ['# 2. per-class thresholds only',
                   f'python eval.py ./configs/{Path(args.tau_cfg_out).name}']
        if args.cfg_out:
            md += ['# 3. thresholds + scale',
                   f'python eval.py ./configs/{Path(args.cfg_out).name}']
        md += ['```\n',
               'Each printed mIoU should match its predicted row above. Per-class '
               'values may differ by a few hundredths: the cache stores `conf` as '
               'float16 and rung 3 is subsampled.\n']
        for p in written:
            md.append(f'`{p}` written.')

    md.append('\n⛔ If pass 3 does not reproduce its prediction, **do not adjust the '
              'number** — find out which side is wrong. `verify_argmax_reorder.py` '
              'says the two rules are identical, so a disagreement means the '
              'config, the split, or the cache is not what this script assumed.\n')

    text = '\n'.join(md)
    print('\n' + text)
    if args.md:
        mp = Path(args.md).expanduser()
        mp.parent.mkdir(parents=True, exist_ok=True)
        mp.write_text(text)
        print(f'written: {mp}')


if __name__ == '__main__':
    main()
