"""
Fit (scale, threshold) on a calibration split, predict the result, write the config.

The counterpart of tau_deploy.py for the scaled-argmax rule. It produces three
things and its whole purpose is that the first two are checkable against the
third:

  <md>          the PREDICTION -- what eval.py should print, from the cache alone
  <split>.txt   the held-out tiles, so the baseline is measured on the same pixels
  <cfg>.py      an mmseg config carrying `class_scale` AND `prob_thd` as lists

⚠️ Run verify_argmax_reorder.py FIRST. It proves the histogram arithmetic below
and the segmentor's rule are the same thing. Without that, a disagreement between
this prediction and eval.py has two possible causes and no way to tell them apart.

⭐ THREE numbers get predicted, not two, because the question is not "does this
beat the published baseline" -- per-class tau already does that. It is "does the
scale add anything ON TOP of the thresholds":

    published tau, no scale     the baseline
    per-class tau, no scale     the existing method
    per-class tau + scale       this

All three on the SAME held-out tiles. The middle row is the one the last row must
beat, and eval.py can reproduce all three from the two configs this writes plus
the base config with an ann_file override.

    python scripts/verify_argmax_reorder.py            # CPU, must pass first
    python scripts/reorder_deploy.py \\
        --cache ~/outputs/loveda_full_all/cache --tau 0.5 --calib 200 --seed 0 \\
        --split-out ~/splits/loveda_reorder_heldout.txt \\
        --cfg-out ~/SegEarth-OV-3/configs/cfg_loveda_reorder.py \\
        --tau-cfg-out ~/SegEarth-OV-3/configs/cfg_loveda_tauonly.py \\
        --md ~/outputs/week4/reorder_deploy.md
"""
import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import labels                                                     # noqa: E402
from tau_oracle import confusion_at, per_class_iou, miou, NBINS   # noqa: E402
from tau_cv import fit as fit_tau                                 # noqa: E402
from argmax_reorder import hist_at, fit_scale, load_full          # noqa: E402


CFG = '''# GENERATED by scripts/reorder_deploy.py -- do not hand-edit.
#
# Fitted on {ncal} calibration tiles (seed {seed}); evaluated on the {nheld}
# DISJOINT tiles listed in the ann_file below.
#
# Predicted from the cached score stack, on those held-out tiles:
#     published tau = {tau}, no scale  ->  mIoU {m_pub:.2f}
#     per-class tau, no scale          ->  mIoU {m_tau:.2f}   ({d_tau:+.2f})
#     per-class tau + class_scale      ->  mIoU {m_all:.2f}   ({d_all:+.2f})
#
# The row that matters is the third against the SECOND: {d_inc:+.2f}. Beating the
# first proves nothing, because per-class tau already does.
_base_ = './{base_cfg}'

model = dict(
    classname_path='./configs/{cls_file}',
    confidence_threshold=0.5,
    # applied to the scores BEFORE the argmax, in the order of {cls_file}:
{scale_comment}
    class_scale=[{scale_list}],
    # applied to the RAW winning score after it, same order:
{thd_comment}
    prob_thd=[{thd_list}],
)

test_dataloader = dict(
    dataset=dict(ann_file='{split}'))
'''

TAU_CFG = '''# GENERATED by scripts/reorder_deploy.py -- the MIDDLE rung.
#
# Per-class thresholds with NO scaling, on the same {nheld} held-out tiles, so the
# scale's contribution is measurable rather than inferred. Predicted mIoU {m_tau:.2f}.
_base_ = './{base_cfg}'

model = dict(
    classname_path='./configs/{cls_file}',
    confidence_threshold=0.5,
{thd_comment}
    prob_thd=[{thd_list}],
)

test_dataloader = dict(
    dataset=dict(ann_file='{split}'))
'''


def main():
    # These runs take tens of minutes and are usually piped to `tee`, which
    # makes Python block-buffer stdout -- so progress vanishes and a healthy
    # job looks hung. Line-buffer explicitly rather than relying on `-u`.
    try:
        sys.stdout.reconfigure(line_buffering=True)
    except Exception:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache', required=True, help='a --cache-full cache')
    ap.add_argument('--tau', type=float, required=True, help='the published τ')
    ap.add_argument('--calib', type=int, default=200)
    ap.add_argument('--subsample', type=int, default=40000)
    ap.add_argument('--objective', choices=['all', 'real'], default='real')
    ap.add_argument('--w-rounds', type=int, default=3)
    ap.add_argument('--tau-rounds', type=int, default=3)
    ap.add_argument('--seed', type=int, default=0)
    ap.add_argument('--split-out', required=True)
    ap.add_argument('--cfg-out', default=None)
    ap.add_argument('--tau-cfg-out', default=None)
    ap.add_argument('--base-cfg', default='cfg_loveda.py')
    ap.add_argument('--cls-file', default='cls_loveda.txt')
    ap.add_argument('--md', default=None)
    args = ap.parse_args()

    LB = labels.from_cache(args.cache)
    nc, bg = LB.n, LB.bg - 1
    print(f'  classes: {LB}')

    files = sorted(Path(args.cache).expanduser().glob('*.npz'))
    T = len(files)
    if args.calib >= T:
        raise SystemExit(f'--calib {args.calib} but only {T} tiles')
    print(f'{T} tiles | published τ = {args.tau} | calib {args.calib}\n')

    rng = np.random.default_rng(args.seed)
    S, G, PT = load_full(files, args.subsample, nc, NBINS, rng)

    idx = rng.permutation(T)
    cal, held = idx[:args.calib], idx[args.calib:]

    # ---- the held-out tile list, written before anything is fitted on it
    stems = sorted(files[i].stem for i in held)
    sp = Path(args.split_out).expanduser()
    sp.parent.mkdir(parents=True, exist_ok=True)
    sp.write_text('\n'.join(stems) + '\n')
    print(f'\nheld-out split -> {sp}  ({len(stems)} tiles)')

    Scal, Gcal = S[cal].reshape(-1, nc), G[cal].reshape(-1)
    Shel, Ghel = S[held].reshape(-1, nc), G[held].reshape(-1)
    ones = np.ones(nc)

    # ---- rung 1 and 2: no scale. EXACT, from the per-tile histograms.
    Hh = PT[held].sum(0).astype(np.int64)
    taus_only = fit_tau(PT[cal].sum(0).astype(np.int64), bg, NBINS,
                        objective=args.objective)
    m_pub = miou(confusion_at(Hh, np.full(nc, args.tau), bg, NBINS))
    m_tau = miou(confusion_at(Hh, taus_only, bg, NBINS))

    # ---- rung 3: fit the scale, then refit tau underneath it
    print('\nfitting the scale:')
    w, _ = fit_scale(Scal, Gcal, bg, nc, NBINS, np.round(
        np.exp(np.linspace(np.log(0.40), np.log(2.50), 11)), 3),
        args.objective, args.w_rounds, args.tau_rounds)
    taus_all = fit_tau(hist_at(Scal, Gcal, w, nc, NBINS), bg, NBINS,
                       objective=args.objective)
    Hh_w = hist_at(Shel, Ghel, w, nc, NBINS)
    m_all = miou(confusion_at(Hh_w, taus_all, bg, NBINS))

    # ⚠️ rung 3 is computed on SUBSAMPLED pixels while rungs 1-2 are exact, so
    # the same subsample is used to re-measure rung 2. Mixing an exact number
    # with a subsampled one would attribute the sampling difference to the scale.
    Hh_sub = hist_at(Shel, Ghel, ones, nc, NBINS)
    m_tau_sub = miou(confusion_at(Hh_sub, taus_only, bg, NBINS))
    m_pub_sub = miou(confusion_at(Hh_sub, np.full(nc, args.tau), bg, NBINS))
    drift = abs((m_tau - m_pub) - (m_tau_sub - m_pub_sub))

    pc_tau = per_class_iou(confusion_at(Hh, taus_only, bg, NBINS)) \
        - per_class_iou(confusion_at(Hh, np.full(nc, args.tau), bg, NBINS))
    pc_all = per_class_iou(confusion_at(Hh_w, taus_all, bg, NBINS)) \
        - per_class_iou(confusion_at(Hh_sub, taus_only, bg, NBINS))

    d_tau = m_tau - m_pub
    d_inc = m_all - m_tau_sub
    # ⚠️ Rung 3's raw subsampled absolute carries the subsample's own offset --
    # on LoveDA that was +0.28, so the naive prediction missed eval.py by 0.25
    # while the INCREMENT matched to 0.03. Debias it by adding the increment to
    # the EXACT rung 2, so the printed absolute is the one eval.py will print.
    m_all_dbi = m_tau + d_inc
    d_all = m_all_dbi - m_pub

    md = ['# Scaled argmax — deployment fit and prediction\n',
          f'- cache: `{args.cache}`  |  tiles: **{T}**  |  calibration: '
          f'**{args.calib}**, held out: **{len(stems)}** (seed {args.seed})',
          f'- published τ: **{args.tau}**  |  objective **`{args.objective}`**\n',
          '## Predicted, on the held-out tiles\n',
          '| rung | scale | thresholds | mIoU |', '|---|---|---|---|',
          f'| baseline | — | published {args.tau} | {m_pub:.2f} |',
          f'| **per-class τ** | — | fitted | **{m_tau:.2f}** ({d_tau:+.2f}) |',
          f'| **+ class scale** | fitted | fitted | **{m_all_dbi:.2f}** '
          f'({m_all_dbi - m_pub:+.2f}) |',
          f'\n⚠️ Rung 3 is quoted **debiased**: the exact rung 2 plus the '
          f'subsampled increment. Its raw subsampled absolute is {m_all:.2f}, '
          f'which carries the subsample\'s own offset and is NOT what eval.py '
          f'prints — the offset cancels in the increment but not in the level.\n',
          f'⭐ **The increment that matters is {d_inc:+.2f}** — the scale over the '
          'thresholds, both measured on the same subsampled pixels. Beating the '
          'baseline proves nothing here; per-class τ already does that.\n',
          f'⚠️ Rungs 1–2 are exact over every pixel; rung 3 is over a '
          f'{args.subsample}-px/tile subsample. Rung 2 recomputed on that same '
          f'subsample gives {m_tau_sub:.2f}, a drift of **{drift:.3f}** mIoU — the '
          'increment above uses the subsampled rung 2, so the sampling difference '
          'is not credited to the scale.\n']

    # ⚠️ BOTH threshold vectors, because this script writes BOTH configs and they
    # carry different ones: `taus_only` is fitted with no scale (rung 2), `taus_all`
    # is refitted underneath the scale (rung 3). Printing only the second invites
    # exactly the mistake it caused on Potsdam -- the tau-only config's printed
    # vector was checked against the wrong column and read as a bug.
    md += ['## Fitted parameters\n',
           '| class | scale `w` | τ **without** scale *(rung 2 cfg)* | '
           'τ **under** scale *(rung 3 cfg)* |', '|---|---|---|---|']
    for c in range(nc):
        md.append(f'| {LB.names[c]}{" *(catch-all)*" if c == bg else ""} | '
                  f'**{w[c]:.3f}** | {taus_only[c]:.3f} | {taus_all[c]:.3f} |')
    md.append(f'\nThe segmentor echoes whichever vector it loads, so '
              f'`grep "per-class prob_thd" <log>` should match the third column for '
              f'the tau-only config and the fourth for the scaled one.\n')

    # ⭐ ABSOLUTE per-class IoU for all three rungs, not just deltas. eval.py
    # prints absolutes, so deltas force the reader to subtract two tables by hand
    # and a per-class disagreement stays invisible until someone does. On Potsdam
    # rungs 2 and 3 missed by 1.2-1.6 mIoU while rung 1 matched to 0.03, and the
    # cause was only locatable per class.
    iou_a = per_class_iou(confusion_at(Hh, np.full(nc, args.tau), bg, NBINS))
    iou_b = per_class_iou(confusion_at(Hh, taus_only, bg, NBINS))
    iou_c = per_class_iou(confusion_at(Hh_w, taus_all, bg, NBINS))
    md += ['\n## Predicted per-class IoU — compare directly against eval.py\n',
           '| class | A published τ | B per-class τ | C + scale | B−A | C−B |',
           '|---|---|---|---|---|---|']
    for c in range(nc):
        md.append(f'| {LB.names[c]}{" *(catch-all)*" if c == bg else ""} | '
                  f'{iou_a[c]:.2f} | {iou_b[c]:.2f} | {iou_c[c]:.2f} | '
                  f'{pc_tau[c]:+.2f} | **{pc_all[c]:+.2f}** |')
    md.append('\n⚠️ Every column is a **prediction**. Compare each against the '
              'matching `eval.py` table class by class — an aggregate that agrees '
              'can hide two classes that disagree in opposite directions, and an '
              'aggregate that disagrees says nothing about which class caused it.\n')

    # ---- configs
    def block(vals, fmt='{:.3f}'):
        return '\n'.join(f'    #   {LB.names[c]:<14} {fmt.format(vals[c])}'
                         for c in range(nc))

    written = []
    if args.tau_cfg_out:
        p = Path(args.tau_cfg_out).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(TAU_CFG.format(
            nheld=len(stems), m_tau=m_tau, base_cfg=args.base_cfg,
            cls_file=args.cls_file, thd_comment=block(taus_only), split=sp,
            thd_list=', '.join(f'{t:.3f}' for t in taus_only)))
        written.append(p)
    if args.cfg_out:
        p = Path(args.cfg_out).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(CFG.format(
            ncal=args.calib, seed=args.seed, nheld=len(stems), tau=args.tau,
            m_pub=m_pub, m_tau=m_tau, m_all=m_all_dbi, d_tau=d_tau, d_all=d_all,
            d_inc=d_inc, base_cfg=args.base_cfg, cls_file=args.cls_file,
            scale_comment=block(w), scale_list=', '.join(f'{x:.3f}' for x in w),
            thd_comment=block(taus_all), split=sp,
            thd_list=', '.join(f'{t:.3f}' for t in taus_all)))
        written.append(p)

    if written:
        md += ['\n## Run it — three passes, same tiles\n', '```bash',
               'cd ~/SegEarth-OV-3',
               '# 1. baseline, restricted to the held-out tiles',
               f'python eval.py ./configs/{args.base_cfg} \\',
               f'  --cfg-options test_dataloader.dataset.ann_file={sp}']
        if args.tau_cfg_out:
            md += ['# 2. per-class thresholds only',
                   f'python eval.py ./configs/{Path(args.tau_cfg_out).name}']
        if args.cfg_out:
            md += ['# 3. thresholds + scale',
                   f'python eval.py ./configs/{Path(args.cfg_out).name}']
        md += ['```\n',
               'Each printed mIoU should match its predicted row above. Per-class '
               'values may differ by a few hundredths: the cache stores `conf` as '
               'float16 and rung 3 is subsampled.\n']
        for p in written:
            md.append(f'`{p}` written.')

    md.append('\n⛔ If pass 3 does not reproduce its prediction, **do not adjust the '
              'number** — find out which side is wrong. `verify_argmax_reorder.py` '
              'says the two rules are identical, so a disagreement means the '
              'config, the split, or the cache is not what this script assumed.\n')

    text = '\n'.join(md)
    print('\n' + text)
    if args.md:
        mp = Path(args.md).expanduser()
        mp.parent.mkdir(parents=True, exist_ok=True)
        mp.write_text(text)
        print(f'written: {mp}')


if __name__ == '__main__':
    main()
