"""
Turn the fitted per-class thresholds into something the real pipeline runs.

WHY THIS EXISTS. §9b's +1.18 mIoU is arithmetic on a cached (gt, pred, conf-bin)
histogram. That shortcut is verified exact against brute force, but "provably
equivalent" and "we ran it" are different claims, and the gain is now the
project's headline. This script closes the gap: it fits the thresholds, writes
the held-out tile list, emits an mmseg config, and prints the mIoU the GPU run
must reproduce. If eval.py disagrees with the prediction below by more than a
few hundredths, the method is not what the histogram said it was.

WHAT IT WRITES

  <split>.txt   tile stems NOT used for calibration, in mmseg `ann_file` format.
                Evaluation must be restricted to these or the comparison is a leak.
  <cfg>.py      an mmseg config with `prob_thd` as a LIST. The patched segmentor
                indexes it by the argmax class; a scalar is unchanged behaviour.

THE TWO NUMBERS TO CHECK. Both are on the held-out tiles only:

  published τ  -- what eval.py gives with the baseline config restricted to the split
  fitted τ     -- what eval.py gives with the emitted config

Their difference is the claim. The absolute values will not match the full-split
47.37, because these are a subset.

⚠️ Expect ~0.01-0.02 of disagreement, not 0.000. `conf` is cached as float16
(WEEK1_RESULTS §7.7) and the histogram quantises it to 200 bins, so pixels within
a bin width of a threshold can fall on either side. A larger gap is a real
discrepancy and must be chased, not rounded away.

    python scripts/tau_deploy.py --cache ~/outputs/week3_fused/cache --tau 0.5 \
        --calib 200 --split-out ~/splits/loveda_heldout.txt \
        --cfg-out ~/SegEarth-OV-3/configs/cfg_loveda_perclass.py
"""
import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import labels                                                    # noqa: E402
from tau_oracle import confusion_at, miou, per_class_iou, NBINS  # noqa: E402
from tau_cv import per_tile_hists, fit                           # noqa: E402


CFG = '''# GENERATED by scripts/tau_deploy.py -- do not hand-edit, regenerate.
#
# Per-class thresholds fitted by coordinate ascent on {ncal} calibration tiles
# drawn from this split with seed {seed}, maximising land-cover mIoU (the
# catch-all class is excluded from the objective; see WEEK3_RESULTS.md 9b).
# The evaluation tiles below are DISJOINT from the calibration tiles.
#
# Predicted from the cached histogram, on these held-out tiles:
#     published tau = {tau}   ->  mIoU {m_pub:.2f}
#     per-class tau           ->  mIoU {m_fit:.2f}   ({delta:+.2f})
#
# Run BOTH to check: this config, and {base_cfg} with `ann_file` added, so the
# baseline is measured on the same pixels.
_base_ = './{base_cfg}'

model = dict(
    classname_path='./configs/{cls_file}',
    confidence_threshold=0.5,
    # one threshold per class, in the order of {cls_file}:
{thd_comment}
    prob_thd=[{thd_list}],
)

test_dataloader = dict(
    dataset=dict(ann_file='{split}'))
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache', required=True)
    ap.add_argument('--tau', type=float, required=True, help='the published τ')
    ap.add_argument('--calib', type=int, default=200,
                    help='calibration tiles. 200 is where every draw turned '
                         'positive in the learning curve (WEEK3 §9b).')
    ap.add_argument('--objective', choices=['all', 'real'], default='real',
                    help="what the FIT maximises. 'real' excludes the catch-all so "
                         "the search cannot buy mIoU by repairing an over-predicted "
                         "background at land cover's expense. Reporting is full mIoU.")
    ap.add_argument('--seed', type=int, default=0)
    ap.add_argument('--split-out', required=True)
    ap.add_argument('--cfg-out', default=None)
    ap.add_argument('--base-cfg', default='cfg_loveda.py')
    ap.add_argument('--cls-file', default='cls_loveda.txt')
    ap.add_argument('--md', default=None)
    args = ap.parse_args()

    LB = labels.from_cache(args.cache)
    nc, bg = LB.n, LB.bg - 1
    files = sorted(Path(args.cache).expanduser().glob('*.npz'))
    n = len(files)
    if args.calib >= n:
        raise SystemExit(f'--calib {args.calib} leaves nothing to evaluate on ({n} tiles)')
    print(f'  classes: {LB}\n{n} tiles | calibration {args.calib} | '
          f'held out {n - args.calib} | published τ = {args.tau}\n')

    PT = per_tile_hists(files, nc, NBINS)
    rng = np.random.default_rng(args.seed)
    idx = rng.permutation(n)
    cal, held = idx[:args.calib], idx[args.calib:]

    taus = fit(PT[cal].sum(0).astype(np.int64), bg, NBINS, objective=args.objective)
    # tau[bg] can never change an assignment -- a sub-threshold background pixel is
    # reassigned to background. Pin it to the published value so the emitted config
    # does not imply a decision that was never made.
    taus[bg] = args.tau

    Hh = PT[held].sum(0).astype(np.int64)
    C_pub = confusion_at(Hh, np.full(nc, args.tau), bg, NBINS)
    C_fit = confusion_at(Hh, taus, bg, NBINS)
    m_pub, m_fit = miou(C_pub), miou(C_fit)
    d = per_class_iou(C_fit) - per_class_iou(C_pub)

    stems = sorted(Path(files[i]).stem for i in held)
    sp = Path(args.split_out).expanduser()
    sp.parent.mkdir(parents=True, exist_ok=True)
    sp.write_text('\n'.join(stems) + '\n')

    md = ['# Per-class τ — deployment configuration\n',
          f'- cache: `{args.cache}`  |  seed **{args.seed}**  |  fit objective '
          f'**`{args.objective}`**',
          f'- calibration **{args.calib}** tiles, evaluation **{len(held)}** tiles, disjoint',
          f'- split file: `{sp}`\n',
          '## Thresholds\n', '| class | published | fitted |', '|---|---|---|']
    for c in range(nc):
        if c == bg:
            md.append(f'| {LB.names[c]} *(catch-all)* | {args.tau} | '
                      f'— *(cannot change any assignment)* |')
        else:
            md.append(f'| {LB.names[c]} | {args.tau} | **{taus[c]:.3f}** |')
    md += [f'\nSpread **{min(taus[c] for c in range(nc) if c != bg):.3f}–'
           f'{max(taus[c] for c in range(nc) if c != bg):.3f}** against a single '
           f'{args.tau}. That spread is the argument: one global value is wrong for '
           'different classes in opposite directions.\n',
           '## What the GPU run must reproduce\n',
           '| rule | predicted mIoU on the held-out tiles |', '|---|---|',
           f'| published τ = {args.tau} | **{m_pub:.2f}** |',
           f'| per-class τ | **{m_fit:.2f}** |',
           f'| **Δ** | **{m_fit - m_pub:+.2f}** |\n',
           '⚠️ Predicted from the cached float16 `conf` binned to 200 levels. Agreement '
           'to ~0.01–0.02 confirms the histogram shortcut; a larger gap is a real '
           'discrepancy and the method claim waits on it.\n',
           '## Predicted per-class Δ IoU\n', '| class | Δ |', '|---|---|']
    for c in range(nc):
        if np.isfinite(d[c]):
            md.append(f'| {LB.names[c]}{" *(catch-all)*" if c == bg else ""} | '
                      f'**{d[c]:+.2f}** |')
    real = float(np.nansum([d[c] for c in range(nc) if c != bg]))
    md.append(f'\n`{LB.names[bg]}` **{d[bg]:+.2f}**, the {nc - 1} real classes '
              f'**{real:+.2f}** in aggregate.\n')

    if args.cfg_out:
        thd_comment = '\n'.join(f'    #   {LB.names[c]:<14s} {taus[c]:.3f}'
                                for c in range(nc))
        cp = Path(args.cfg_out).expanduser()
        cp.parent.mkdir(parents=True, exist_ok=True)
        cp.write_text(CFG.format(
            ncal=args.calib, seed=args.seed, tau=args.tau, m_pub=m_pub, m_fit=m_fit,
            delta=m_fit - m_pub, base_cfg=args.base_cfg, cls_file=args.cls_file,
            thd_comment=thd_comment, split=sp,
            thd_list=', '.join(f'{t:.3f}' for t in taus)))
        md += ['## Run it\n', '```bash', 'cd ~/SegEarth-OV-3',
               '# baseline, restricted to the SAME held-out tiles',
               f'python eval.py ./configs/{args.base_cfg} \\',
               f'  --cfg-options test_dataloader.dataset.ann_file={sp}',
               '# the method',
               f'python eval.py ./configs/{cp.name}', '```\n',
               f'`{cp}` written.\n']

    text = '\n'.join(md)
    print('\n' + text)
    if args.md:
        mp = Path(args.md).expanduser()
        mp.parent.mkdir(parents=True, exist_ok=True)
        mp.write_text(text)
        print(f'written: {mp}')


if __name__ == '__main__':
    main()
